const { error: dbError } = await supabase.from("resume_submissions").insert({
  psid: submissionId,
  agency: data.agency ?? null, 
  name: data.name ?? null,
  dob: data.dob ?? null, 
  nationality: data.nationality ?? null,
  country: data.country ?? null, 
  city: data.city ?? null,
  phone: data.phone ?? null, 
  email: data.email ?? null,
  job_type: data.jobType ?? null, 
  work_arrange: data.workArrange ?? null,
  availability: data.availability ?? null, 
  salary: data.salary || null,
  experience: data.experience ?? null,
  job1_title: data.job1Title ?? null, 
  job1_company: data.job1Company ?? null, 
  job1_dates: data.job1Dates ?? null,
  job2_title: data.job2Title || null, 
  job2_company: data.job2Company || null, 
  job2_dates: data.job2Dates || null,
  job3_title: data.job3Title || null, 
  job3_company: data.job3Company || null, 
  job3_dates: data.job3Dates || null,
  skills: data.skills ?? null, 
  certs: data.certs || null,
  education: data.education ?? null, 
  languages: data.languages ?? null,
  pdf_url: pdfUrl,
  passport_photo_url: data.passportPhotoUrl || null,   // NEW
});
